CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "role" varchar NOT NULL,
  "gender" varchar NOT NULL
);

CREATE TABLE "movies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(150) NOT NULL,
  "genres" varchar(59) NOT NULL,
  "year" varchar(255) NOT NULL,
  "photo" varchar(255)
);

CREATE TABLE "profile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "photo_user" varchar,
  "bio" varchar,
  "address" varchar,
  "age" integer,
  "user_id" integer UNIQUE
);

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "profile" ("user_id");
